### PR TITLE
jobs: hook up more coreos/ repos

### PR DESCRIPTION
**Pull request by jlebon**
Hook up a bunch more repos under the `coreos/` org that don't have much
CI yet.

### CODE REVIEW

**Comment by cgwalters** [comment]
GO GO GADGET CI!

**Comment by cgwalters** [comment]
After merging things like this, is any manual action required?

**Comment by jlebon** [comment]
> After merging things like this, is any manual action required?

Right now, yes. You have to run `[seed-github-ci](https://jenkins-coreos-ci.apps.ci.centos.org/job/seed-github-ci/)`, then start the scan on the new multibranch jobs that were created. Automating that bit is on the list!

**Comment by jlebon** [comment]
Actually, you don't have to start the scan, that bit happens automatically.

**Pull request merged**
