### PR TITLE
jobs/test-override: on mechanical streams, build on top of known good version

### PR DESCRIPTION
**Pull request by jlebon**
When testing a rawhide update, we should be testing on top of a rawhide build that we know has worked. Otherwise, the test may fail for any arbitrary reason. Since rawhide is not locked, we do this by autolocking on top of the most recent build that contains all the relevant arches.

See also: https://github.com/coreos/fedora-coreos-releng-automation/issues/181

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/coreos-assembler/pull/3701
Requires: https://github.com/coreos/fedora-coreos-releng-automation/pull/183

Also still need to test this.

**Comment by jlebon** [comment]
Tested working now!

**Comment by jlebon** [comment]
One detail here is that this assumes that any build in `builds.json` with the matching arches is good, but that's only true if `EARLY_ARCH_JOBS` is unset (otherwise, it's possible that e.g. testiso tests actually failed). Unset is the default, but maybe in the future we should actually check the release index instead since those are builds which actually completed successfully. (And of course, we'll have a similar issue if we add cloud testing in the future.)

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
